/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    Drawer: typeof import('./src/components/ui/drawer/Drawer.vue')['default']
    DrawerClose: typeof import('./src/components/ui/drawer/DrawerClose.vue')['default']
    DrawerComponent: typeof import('./src/components/DrawerComponent.vue')['default']
    DrawerContent: typeof import('./src/components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./src/components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./src/components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./src/components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./src/components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./src/components/ui/drawer/DrawerTitle.vue')['default']
    DrawerTrigger: typeof import('./src/components/ui/drawer/DrawerTrigger.vue')['default']
    FabButton: typeof import('./src/components/FabRoutingButton.vue')['default']
    FabRoutingButton: typeof import('./src/components/FabRoutingButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    SlideOverPanel: typeof import('./src/components/ui/SlideOverPanel.vue')['default']
    TradeIdeaCardView: typeof import('./src/components/trade-ideas/TradeIdeaCardView.vue')['default']
    TradeIdeaForm: typeof import('./src/components/trade-ideas/TradeIdeaForm.vue')['default']
  }
}
