"""inital migration

Revision ID: 10ba7df0ad2e
Revises: 
Create Date: 2025-07-30 14:30:23.483573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '10ba7df0ad2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('max_risk_percentage', sa.Float(), nullable=False),
    sa.Column('max_active_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_idea',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('WATCHING', 'IN_PROGRESS', 'INVALIDATED', 'LIVE', name='tradeideastatus'), nullable=True),
    sa.Column('entry_min', sa.Float(), nullable=True),
    sa.Column('entry_max', sa.Float(), nullable=True),
    sa.Column('catalysts', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idea_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_prices', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_trade',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('trade_idea_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_size', sa.Integer(), nullable=False),
    sa.Column('entry_price_avg', sa.Float(), nullable=False),
    sa.Column('exit_price_avg', sa.Float(), nullable=True),
    sa.Column('commissions', sa.Float(), nullable=True),
    sa.Column('enter_date', sa.DateTime(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('net_gain_loss', sa.Float(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_prices', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trade_idea_id'], ['trade_idea.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_idea_id')
    )
    op.create_table('annotation',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('live_trade_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['live_trade_id'], ['live_trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    op.drop_table('live_trade')
    op.drop_table('trade_idea')
    op.drop_table('account')
    # ### end Alembic commands ###
