"""rename type to annotation_type

Revision ID: 26e898071fb3
Revises: f7d1998a730b
Create Date: 2025-08-12 11:24:28.572324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '26e898071fb3'
down_revision: Union[str, None] = 'f7d1998a730b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()

    # 1) add new column with a server default to satisfy SQLite
    op.add_column(
        "annotation",
        sa.Column("annotation_type", sa.String(length=16), nullable=True, server_default="note"),
    )

    # 2) copy the old values over
    op.execute("UPDATE annotation SET annotation_type = type")

    # 3) enforce NOT NULL and drop the server default; drop old column
    with op.batch_alter_table("annotation", recreate="always") as batch:
        batch.alter_column(
            "annotation_type",
            existing_type=sa.String(length=16),
            nullable=False,
            server_default=None,
        )
        batch.drop_column("type")

    # live_trade / trade_idea JSON nullability and indexes
    with op.batch_alter_table("live_trade", recreate="always") as batch:
        batch.alter_column("target_prices", existing_type=sa.JSON(), nullable=False)
        batch.create_index(op.f("ix_live_trade_symbol"), ["symbol"], unique=False)

    with op.batch_alter_table("trade_idea", recreate="always") as batch:
        batch.alter_column("target_prices", existing_type=sa.JSON(), nullable=False)
        batch.create_index(op.f("ix_trade_idea_symbol"), ["symbol"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_idea_symbol'), table_name='trade_idea')
    op.alter_column('trade_idea', 'target_prices',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_live_trade_symbol'), table_name='live_trade')
    op.alter_column('live_trade', 'target_prices',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_column('live_trade', 'date')
    op.add_column('annotation', sa.Column('type', sa.VARCHAR(), nullable=False))
    op.drop_column('annotation', 'annotation_type')
    # ### end Alembic commands ###
