"""inital migration

Revision ID: 778328b9c311
Revises: 
Create Date: 2025-07-24 08:57:35.013627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '778328b9c311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('max_risk_percentage', sa.Float(), nullable=False),
    sa.Column('max_active_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_idea',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('WATCHING', 'IN_PROGRESS', 'INVALIDATED', 'LIVE', name='tradeideastatus'), nullable=False),
    sa.Column('setup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('entry_min', sa.Float(), nullable=True),
    sa.Column('entry_max', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target_prices', sa.JSON(), nullable=True),
    sa.Column('catalysts', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idea_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_idea')
    op.drop_table('account')
    # ### end Alembic commands ###
